name: pix_theta_utils
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  http: ^1.5.0
  http_auth: ^1.0.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
